project:
  type: website
  output-dir: docs

website:
  title: "franceslinyc"
  open-graph: true
  page-footer: 
    left: "Made with [Quarto](https://quarto.org)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - education.qmd
      - experience.qmd
      - posts/index.qmd
      - whatelse.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



